### PR TITLE
feat: included a menu for display on mobile

### PR DESCRIPTION
**Pull request by daniel99korban**
I am collaborating for the first time on a well-known open-source project. I contributed by implementing a responsive menu. Although it may not be the most essential feature, I am very pleased with the results and learned a lot throughout the process. My sincere thanks to the community!

screen-cap-1

screen-cap-2

### CODE REVIEW

**Comment by GitMensch** [comment]
Can you please also post a "before" screenshot from that device?

**Comment by daniel99korban** [comment]
Yes, of course! Below you can see two instances of breakpoints.

screen-cap-2

screen-cap-1

**Comment by daniel99korban** [comment]
> Can you please also post a "before" screenshot from that device?

Yes, of course! Below you can see two instances of breakpoints.

screen-cap-2

screen-cap-1

**Comment by daiyam** [comment]
@daniel99korban Thank you. Sorry for the delay.

**Comment by daniel99korban** [comment]
Hi, no problem! Thank you so much for everything!

**Pull request merged**
