### PR TITLE
Add anchors to headers using anchor.js

### PR DESCRIPTION
**Pull request by evebyte**
Hi,

I noticed the website is missing anchors on the headers, so I added them using anchor.js.

This should help people deep link installation instructions.

PS
This is my first FOSS contribution, if you have any notes or feedback it would be appreciated :-)

### CODE REVIEW

**Comment by GitMensch** [comment]
It means that all headlines get an anchor (which auto-adds that to this headline, too), then removes this single anchor.
LGTM

**Comment by GitMensch** [comment]
Note: as we use a static generator to create the page in the first place, it would be good if the headlines would be auto-added there, not in the DOM after reading the page by some script that again needs to be run in the browser.
I therefore consider this more as a temporary solution which should be replaced by an option in the static generator.

**Comment by paulcarroty** [comment]
Yeah, the PRs are welcome.

**Comment by evebyte** [comment]
@paulcarroty No worries. Sorry for any misunderstanding, this was my first contribution. I'll try to add a little more context in the comments in future PRs.

@GitMensch  I'll look into an implementation using a Jekyll plugin instead of this script that runs after the site is generated.

Thank you both for taking the time to look over and merge my PR. If there is anything I can improve on please let me know. :+1:

**Pull request merged**
