### PR TITLE
add metadata_expire to avoid hash mismatch

### PR DESCRIPTION
**Pull request by paulcarroty**
https://github.com/VSCodium/vscodium/issues/855

### CODE REVIEW

**Comment by stripedpajamas** [comment]
Can you resolve the conflicts?

**Comment by GitMensch** [comment]
Conflicts resolved, but I don't know if that is still the "correct" thing to do with the new URL. @paulcarroty can you drop a note, please?

**Comment by daiyam** [comment]
The issue was due to that all files were regenerated if any file was missing. At that time, it happened a lot due to network errors when publishing them.
I've made necessary changes in the workflows so that only missing files are generated and they retry to publish if there is a network issue (10 times with increasing delay between theme).

So @paulcarroty, does this PR still necessary?

**Comment by paulcarroty** [comment]
Thx for the resolving. Yeah 'cause it's popular `dnf` and `yum` issue when package manager use old metadata and trying to download the files which are not around anymore.

**Pull request merged**
