### PR TITLE
install: add a note of a mirror

### PR DESCRIPTION
**Pull request by jtagcat**
ping @paulcarroty, jfyi

### CODE REVIEW

**Comment by PalinuroSec** [comment]
i have experienced the same issue too, in fact i have recently replaced the previous download link with download.vscodium.com which is a cdn service provided by bunny.net with origin shield enabled and proper rules to bypass cache on /debs/dists and /rpms/repodata

we might consider adding a more extensive mirror sectionto the website, but it would be better to perform a little page re-design before that

**Comment by GitMensch** [comment]
@PalinuroSec wrote:

> it would be better to perform a little page re-design before that

That would be possible. What do you have in your mind?

**Comment by paulcarroty** [comment]
I vote for complete redesign, too many issues.

> found that updating `codium` took over fifteen minutes, sometimes timing out,

Do you **really** want this on landing page?? Think twice.

> To use the mirror, you may replace `paulcarroty.gitlab.io/vscodium-deb-rpm-repo` with `vscodium.c7.ee` (URLs with `/rpms`/`/debs`).

I'd recommend to cut it: `you may replace link1 to link2`.

**Comment by jtagcat** [comment]
This is getting noisy for me. Could you please move this discussion to a separate issue or PR, and either merge or close this PR? Thanks.

**Comment by paulcarroty** [comment]
Can you improve it?

**Pull request merged**
